// Generated by CoffeeScript 1.3.3

/*
Criação da função e parâmetros para a fixação da subnav.
*/


(function() {
  var $nav, $win, data, isFixed, navTop, processScroll;

  $win = $(window);

  $nav = $('.subnav');

  navTop = $('.subnav').length && $('.subnav').offset().top - 40;

  isFixed = 0;

  processScroll = function() {
    var i, scrollTop;
    i = 0;
    scrollTop = $win.scrollTop();
    if (scrollTop >= navTop && !isFixed) {
      isFixed = 1;
      return $nav.addClass('subnav-fixed');
    } else if (scrollTop <= navTop && isFixed) {
      isFixed = 0;
      return $nav.removeClass('subnav-fixed');
    }
  };

  processScroll();

  $win.on('scroll', processScroll);

  /*
  Adição da funcionalidade de expandir para as widgets.
  Quando o botão de expandir for clicado irá ser adicionada a classe expanded para a widget.
  */


  $(".expander").on("click", function(e) {
    $(this).parent().parent().toggleClass("expanded");
    return e.preventDefault();
  });

  /*
  Adição da funcionalidade de painel de configuração para as widgets.
  quando o botão de configurações for clicado irá ser adicionada a classe open para o painel de configurações,
  abrindo o mesmo.
  */


  $(".settings-nub").on("click", function(e) {
    $(this).toggleClass("open").parent().parent().find(".settings").toggleClass("open");
    return e.preventDefault();
  });

  /*
  Botando o botão do formulário de configurações para fechar o painel quando o mesmo for clicado.
  */


  $(".settings button").on("click", function(e) {
    if ($(this).hasClass("btn-filtro")) {
      $(this).parent().parent().parent().find(".settings-nub, .settings").toggleClass("open");
    }
    return e.preventDefault();
  });

  /*
  Adição do filtro para indicar as tooltips, todo elemento com o atributo rel='tooltip' irá ter um tooltip,
  com o conteúdo igual ao do atributo title deste mesmo elemento.
  Esse código usa o bootstrap.tooltip que está incluso no bootstrap.min.js
  */


  $("[rel='tooltip']").tooltip();

  /*
  Adição da funcionalidade de altocomplete para os elementos com a classe chosen.
  Este auto complete NÃO contém chamadas em AJAX, ele pega e monta a lista de elementos baseada em um ul ou select.
  Esse código usa o chosen que está incluso no chosen.jquery.min.js
  */


  $(".chosen").chosen({
    no_results_text: "Nenhum resultado encontrado"
  });

  /*
  definição de um atributo para simular o retorno de uma consulta a uma página em ajax para os autocomplete.
  */


  data = {
    items: [
      {
        value: "21",
        name: "21ª: Colégio Estadual Darci Coelho de Souza e Silva"
      }, {
        value: "43",
        name: "22ª: Colégio Municipal Comecinho do Sith"
      }, {
        value: "46",
        name: "23ª: Colégio Municipal Darth Vader Segundo"
      }, {
        value: "54",
        name: "25ª: Colégio Estadual Coizinha da Mamãe"
      }, {
        value: "55",
        name: "26ª: Colégio Estadual Great Scott"
      }, {
        value: "79",
        name: "21ª: Colégio Estadual Doc Emmett Brown"
      }, {
        value: "79",
        name: "21ª Zona Eleitoral"
      }
    ]
  };

  /*
  Adição da funcionalidade de autocomplete, com multiplos itens, para os elementos com a classe autocomplete e para o input de #message-form.
  Este ultimo foi necessária outra configuração pois o label inicial para o elemento é diferente do padrão.
  Esse código usa o AutoSuggest que está incluso no jquery.autosugest.min.js
  */


  $(".autocomplete").autoSuggest(data.items, {
    selectedItemProp: "name",
    searchObjProps: "name",
    startText: "Adicionar filtro",
    emptyText: "Nenhum resultado",
    limitText: "Não é possivel fazer nenhuma outra seleção",
    minChars: 2,
    selectionLimit: 3
  });

  $("#message-form input").autoSuggest(data.items, {
    selectedItemProp: "name",
    searchObjProps: "name",
    startText: "Enviar para",
    emptyText: "Nenhum resultado",
    limitText: "Não é possivel fazer nenhuma outra seleção",
    minChars: 2,
    selectionLimit: 3
  });

  /*
  Adição do efeito de focus/blur para o elemento do autocomplete igual ao comportamento dos inputs padrão.
  */


  $(".as-selections input").focus(function() {
    return $(this).parent().parent().addClass("focus");
  }).blur(function() {
    return $(this).parent().parent().removeClass("focus");
  });

  /*
  Adição da funcionalidade de autocomplete, com apenas 1 item, para os elementos com a classe mun-autocomplete.
  Esse código usa o bootstrap.typeahead que está incluso no bootstrap.min.js
  */


  $(".mun-autocomplete").typeahead({
    source: ['Tocantínia', 'Araguaína', 'Palmas', 'Gurupi', 'Porto Nacional']
  });

  /* Opção com o jquery-autocomplete, não está incluso no código atualmente, está aqui apenas como opção.
   $(".mun-autocomplete").autocomplete {
       data: [
           ['Tocantínia', 1],
           ['Araguaína', 2],
           ['Palmas', 3],
           ['Gurupi', 4],
           ['Porto Nacional', 5]
       ],
       minChars: 2,
       selectFirst: true,
       autoFill: true
     }
  */


  /*
  Adição da funcionalidade de filtro online/offile para a widget de transmissão.
  Quando o botão online/offline for clicado, irá ser adicionada a classe active para este botão e serão escondidos
  os elementos com o data-trans-status que não for compatível com o data-trans-status do botão.
  */


  $('[class^="widget-"] > .form-actions > .btn').on("click", function(e) {
    var $button;
    if ($(this).data("toggle") === "button") {
      $(this).removeClass("transparent");
      $(this).next().toggleClass("transparent");
      $(this).prev().toggleClass("transparent");
      if ($(this).next(".btn").hasClass("active")) {
        $(this).next(".btn").button("toggle");
      }
      if ($(this).prev(".btn").hasClass("active")) {
        $(this).prev(".btn").button("toggle");
      }
    }
    $button = $(this);
    $(this).parent().next().children().children("li").each(function() {
      if ($(this).data("trans-status") === $button.data("trans-status")) {
        return $(this).show();
      } else if (($(this).data("trans-status") !== $button.data("trans-status")) && ($button.hasClass("active"))) {
        return $(this).show();
      } else {
        return $(this).hide();
      }
    });
    return e.preventDefault();
  });

  /*
  Abre as opções (próximo nível, visualizar pessoas e adicionar x) dos itens das listas que estão presentes nas widgets de transmissão, ocorrências e totalização.
  */


  $(".code-wrap .has-item-options li > a").live("click", function(e) {
    $(this).next(".item-options").slideToggle("fast");
    $(this).parent("li").has(".item-options").toggleClass("active");
    return e.preventDefault();
  });

  /*
  Delega aos botões presente nas opções dos itens das listas das widgets para fechar o mini-painel deles quando clicados.
  */


  $(".option-open, .option-close").live("click", function(e) {
    $(this).parent().slideUp("fast");
    $(this).parent().parent("li").toggleClass("active");
    return e.preventDefault();
  });

  /*
  Adiciona a funcionalidade de navegação em 'páginas' para as widgets de ocorrências, totalização e ocorrências da corregedoria.
  Esta funcionalidade simula com o setTimeout o carregamento do próximo nível com AJAX. O código inicial da próxima página já estará
  presente no html, como #step-x, sendo 'x' o número da página que o próximo nível estará. Cada widget terá um nível máximo de páginas,
  e todas já deverão conter o html das páginas (#step-x) presentes no início para os efeitos poderem ser processados.
  ex.:
  
  <div class='content-wrap'>
    <div class='step-1 current'>
      <!-- div atualmente visível na tela -->
    </div>
    <div class='step-2'>
     <!-- div escondida, e aqui irá o conteúdo que será carregado via AJAX -->
    </div>
    <div class='step-3'>
      <!-- div escondida, e aqui irá o conteúdo que será carregado via AJAX -->
    </div>
    ...
  </div>
  
  Com um método com AJAX funcionando de verdade, após a chamada $(this).parents('[class^="widget-"]').find(".loading").addClass("open"),
  no success do método AJAX injetaria-se o HTML de resposta na div $('.step-x').next('.step-x+1').html($meuHTMLdeResposta).
  Em seguida seriam execudados os procedimentos que estão contidos no setTimeout para promover a animação e esconder o painel
  com indicador de carregamento.
  
  A formatação do HTML deve ser idêntica à encontrada dentro das divs .step-x nas widgets.
  */


  // $(".btn-next").live("click", function(e) {
  //   var _this = this;
  //   $(this).parents('[class^="widget-"]').find(".loading").addClass("open");
  //   setTimeout(function() {
  //     $(_this).parents('[class^="step-"]').removeClass("current").addClass("past").next().addClass("current");
  //     $(_this).parents('[class^="widget-"]').find(".loading").removeClass("open");
  //     return $(_this).removeClass("current-clicked");
  //   }, 500);
  //   return e.preventDefault();
  // });

  /*
  Adiciona a navegação de volta entre as 'páginas' das widgets de ocorrências, totalização e ocorrências da corregedoria.
  Para voltar para a 'página' anterior não será necessário ajax, pois a 'página' anterior irá estar apenas 'escondida' à esquerda
  da página atual. A página atual será marcada com a classe current e as páginas anteriores com a classe past.
  As 'próximas' páginas não precisam ter outras classes a não ser a classe step-x.
  ex.:
  
  <div class='content-wrap'>
    <div class='step-1 past'>
      <!-- div escondida, que já tem o conteúdo HTML carregado e cacheado -->
    </div>
    <div class='step-2 past'>
      <!-- div escondida, que já tem o conteúdo HTML carregado e cacheado -->
    </div>
    <div class='step-3 current'>
      <!-- div atualmente visível na tela -->
    </div>
    <div class='step-4'>
      <!-- div escondida, e aqui irá o conteúdo que será carregado via AJAX -->
    </div>
    ...
  </div>
  */


  // $(".btn-prev").live("click", function(e) {
  //   $(this).parent().removeClass("current").prev().addClass("current").removeClass("past");
  //   return e.preventDefault();
  // });

  /*
  Para as widgets de ocorrências e de totalização, deverá ter a opção de dividir ou não as ultimas 'páginas',
  para os usuários que estão em zonas com poucas seções e locais, respectivamente.
  Este método simula a injeção de conteúdo HTML ($htmlOcorrencia, $htmlSecao, $$htmlLocal e $htmlSecaoTot) vindo de uma requisição AJAX.
  Esta função é re-utilizada pelos dois botões de dividir/não dividir das widgets de totalização e ocorrências.
  */


//   $(".btn-divide").live("click", function(e) {
//     var $htmlLocal, $htmlOcorrencia, $htmlSecao, $htmlSecaoTot,
//       _this = this;
//     $htmlOcorrencia = '<a href="#" class="btn btn-small pull-left btn-prev clearfix" rel="tooltip" title="Voltar para seção"><i class="icon-circle-arrow-left"></i></a>\
//                   <a href="#" class="btn btn-small pull-right btn-divide clearfix" data-type="ocorrencia" style="display:none" rel="tooltip" title="Não dividir por seções"><i class="icon-reorder"></i></a>\
//                   <a href="#" class="btn btn-small pull-right btn-divide clearfix not-divided" data-type="ocorrencia" style="display:inline" rel="tooltip" title="Dividir por seções"><i class="icon-columns"></i></a>\
//                   <h3>\
//                     Ocorrências\
//                     <span class="current-place-label">Escola Whatever The Hell they want to name this freaking school D</span>\
//                   </h3>\
//                   <ul class="nav nav-pills nav-stacked hover-inverse">\
//                     <li>\
//                       <a href="#visualizarOcorrencia" data-toggle="modal">\
//                         <span class="label label-icon" rel="tooltip" title="chamado aberto"><i class="icon-check-empty"></i></span>\
//                         <span class="link-text">Chamado A</span>\
//                         <span class="badge pull-right">23ª</span>\
//                       </a>\
//                     </li>\
//                     <li class="falta-mesario">\
//                       <a href="#visualizarOcorrencia" data-toggle="modal">\
//                         <span class="label label-icon" rel="tooltip" title="chamado fechado"><i class="icon-check"></i></span>\
//                         <span class="link-text"><del>Chamado B</del></span>\
//                         <span class="badge pull-right">24ª</span>\
//                         <span class="label pull-right">falta mesário</span>\
//                       </a>\
//                     </li>\
//                     <li>\
//                       <a href="#visualizarOcorrencia" data-toggle="modal">\
//                         <span class="label label-icon" rel="tooltip" title="chamado fechado"><i class="icon-check"></i></span>\
//                         <span class="link-text"><del>Chamado C</del></span>\
//                         <span class="badge pull-right">21ª</span>\
//                       </a>\
//                     </li>\
//                     <li class="parada">\
//                       <a href="#visualizarOcorrencia" data-toggle="modal">\
//                         <span class="label label-icon" rel="tooltip" title="chamado aberto"><i class="icon-check-empty"></i></span>\
//                         <span class="link-text">Chamado D</span>\
//                         <span class="badge pull-right">21ª</span>\
//                         <span class="label pull-right">parada</span>\
//                       </a>\
//                     </li>\
//                     <li>\
//                       <a href="#visualizarOcorrencia" data-toggle="modal">\
//                         <span class="label label-icon" rel="tooltip" title="chamado aberto"><i class="icon-check-empty"></i></span>\
//                         <span class="link-text">Chamado E</span>\
//                         <span class="badge pull-right">23ª</span>\
//                       </a>\
//                     </li>\
//                   </ul>\
//                   <a href="#" class="btn btn-large btn-load-more">Carregar mais</a>\
// \
//                   <script type="text/javascript">\
//                     $("[rel=\'tooltip\']").tooltip();\
//                   </script>';
//     $htmlSecao = '<a href="#" class="btn btn-small pull-left btn-prev clearfix" rel="tooltip" title="Voltar para local"><i class="icon-circle-arrow-left"></i></a>\
//                   <a href="#" class="btn btn-small pull-right btn-divide clearfix" rel="tooltip" data-type="ocorrencia" title="Não dividir por seções"><i class="icon-reorder"></i></a>\
//                   <a href="#" class="btn btn-small pull-right btn-divide clearfix not-divided" data-type="ocorrencia" rel="tooltip" title="Dividir por seções"><i class="icon-columns"></i></a>\
//                   <h3>\
//                     Seções\
//                     <span class="current-place-label">Escola Whatever The Hell they want to name this freaking school D</span>\
//                   </h3>\
//                   <ul class="nav nav-pills nav-stacked has-item-options hover-inverse">\
//                     <li>\
//                       <a href="#">\
//                         <span class="link-text">Seção A</span>\
//                         <span class="badge pull-right">13</span>\
//                       </a>\
//                       <div class="item-options clearfix">\
//                         <a href="#cadastrarOcorrencia" data-toggle="modal" class="btn btn-large pull-left" rel="tooltip" title="Adicionar ocorrência para esta seção"><i class="icon-plus"></i></a>\
//                         <a href="#visualizarPessoas" data-toggle="modal" data-type="secao" class="btn btn-large user-list" rel="tooltip" title="Visualizar equipe desta seção"><i class="icon-user"></i></a>\
//                         <a href="#" class="btn btn-large pull-right btn-next" rel="tooltip" title="Entrar nesta seção"><i class="icon-circle-arrow-right"></i></a>\
//                       </div>\
//                     </li>\
//                     <li class="falta-mesario">\
//                       <a href="#">\
//                         <span class="link-text">Seção B</span>\
//                         <span class="badge pull-right">21</span>\
//                         <span class="label pull-right">falta mesário</span>\
//                       </a>\
//                       <div class="item-options clearfix">\
//                         <a href="#cadastrarOcorrencia" data-toggle="modal" class="btn btn-large pull-left" rel="tooltip" title="Adicionar ocorrência para esta seção"><i class="icon-plus"></i></a>\
//                         <a href="#visualizarPessoas" data-toggle="modal" data-type="secao" class="btn btn-large user-list" rel="tooltip" title="Visualizar equipe desta seção"><i class="icon-user"></i></a>\
//                         <a href="#" class="btn btn-large pull-right btn-next" rel="tooltip" title="Entrar nesta seção"><i class="icon-circle-arrow-right"></i></a>\
//                       </div>\
//                     </li>\
//                     <li>\
//                       <a href="#">\
//                         <span class="link-text">Seção C</span>\
//                         <span class="badge pull-right">31</span>\
//                       </a>\
//                       <div class="item-options clearfix">\
//                         <a href="#cadastrarOcorrencia" data-toggle="modal" class="btn btn-large pull-left" rel="tooltip" title="Adicionar ocorrência para esta seção"><i class="icon-plus"></i></a>\
//                         <a href="#visualizarPessoas" data-toggle="modal" data-type="secao" class="btn btn-large user-list" rel="tooltip" title="Visualizar equipe desta seção"><i class="icon-user"></i></a>\
//                         <a href="#" class="btn btn-large pull-right btn-next" rel="tooltip" title="Entrar nesta seção"><i class="icon-circle-arrow-right"></i></a>\
//                       </div>\
//                     </li>\
//                     <li class="parada">\
//                       <a href="#">\
//                         <span class="link-text">Seção D</span>\
//                         <span class="badge pull-right">18</span>\
//                         <span class="label pull-right">parada</span>\
//                       </a>\
//                       <div class="item-options clearfix">\
//                         <a href="#cadastrarOcorrencia" data-toggle="modal" class="btn btn-large pull-left" rel="tooltip" title="Adicionar ocorrência para esta seção"><i class="icon-plus"></i></a>\
//                         <a href="#visualizarPessoas" data-toggle="modal" data-type="secao" class="btn btn-large user-list" rel="tooltip" title="Visualizar equipe desta seção"><i class="icon-user"></i></a>\
//                         <a href="#" class="btn btn-large pull-right btn-next" rel="tooltip" title="Entrar nesta seção"><i class="icon-circle-arrow-right"></i></a>\
//                       </div>\
//                     </li>\
//                     <li>\
//                       <a href="#">\
//                         <span class="link-text">Seção E</span>\
//                         <span class="badge pull-right">1</span>\
//                       </a>\
//                       <div class="item-options clearfix">\
//                         <a href="#cadastrarOcorrencia" data-toggle="modal" class="btn btn-large pull-left" rel="tooltip" title="Adicionar ocorrência para esta seção"><i class="icon-plus"></i></a>\
//                         <a href="#visualizarPessoas" data-toggle="modal" data-type="secao" class="btn btn-large user-list" rel="tooltip" title="Visualizar equipe desta seção"><i class="icon-user"></i></a>\
//                         <a href="#" class="btn btn-large pull-right btn-next" rel="tooltip" title="Entrar nesta seção"><i class="icon-circle-arrow-right"></i></a>\
//                       </div>\
//                     </li>\
//                   </ul>\
// \
//                   <script type="text/javascript">\
//                     $("[rel=\'tooltip\']").tooltip();\
//                   </script>';
//     $htmlLocal = '<a href="#" class="btn btn-small pull-left btn-prev clearfix" rel="tooltip" title="Voltar para município"><i class="icon-circle-arrow-left"></i></a>\
//                   <a href="#" class="btn btn-small pull-right btn-divide clearfix" rel="tooltip" data-type="totalizacao" title="Não dividir por locais"><i class="icon-reorder"></i></a>\
//                   <a href="#" class="btn btn-small pull-right btn-divide clearfix not-divided" rel="tooltip" data-type="totalizacao" title="Dividir por locais"><i class="icon-columns"></i></a>\
//                   <h3>\
//                     Locais\
//                     <span class="current-place-label">Município A</span>\
//                   </h3>\
//                   <ul class="nav nav-pills nav-stacked has-item-options hover-inverse">\
//                     <li>\
//                       <a href="#">\
//                         <span class="link-text">Escola A</span>\
//                         <div class="progress progress-info pull-right">\
//                           <div class="bar" style="width: 60%;">\
//                             <span>120 de 220</span>\
//                           </div>\
//                         </div>\
//                       </a>\
//                       <div class="item-options clearfix">\
//                         <a href="#visualizarPessoas" data-toggle="modal" data-type="local" class="btn btn-large pull-left" rel="tooltip" title="Visualizar equipe deste local"><i class="icon-user"></i></a>\
//                         <a href="#" class="btn btn-large pull-right btn-next" rel="tooltip" title="Entrar neste local"><i class="icon-circle-arrow-right"></i></a>\
//                       </div>\
//                     </li>\
//                     <li>\
//                       <a href="#">\
//                         <span class="link-text">Escola B</span>\
//                         <div class="progress progress-success pull-right">\
//                           <div class="bar" style="width: 80%;">\
//                             <span>200 de 220</span>\
//                           </div>\
//                         </div>\
//                       </a>\
//                       <div class="item-options clearfix">\
//                         <a href="#visualizarPessoas" data-toggle="modal" data-type="local" class="btn btn-large pull-left" rel="tooltip" title="Visualizar equipe deste local"><i class="icon-user"></i></a>\
//                         <a href="#" class="btn btn-large pull-right btn-next" rel="tooltip" title="Entrar neste local"><i class="icon-circle-arrow-right"></i></a>\
//                       </div>\
//                     </li>\
//                     <li>\
//                       <a href="#">\
//                         <span class="link-text">Escola C</span>\
//                         <div class="progress progress-info pull-right">\
//                           <div class="bar" style="width: 60%;">\
//                             <span>120 de 220</span>\
//                           </div>\
//                         </div>\
//                       </a>\
//                       <div class="item-options clearfix">\
//                         <a href="#visualizarPessoas" data-toggle="modal" data-type="local" class="btn btn-large pull-left" rel="tooltip" title="Visualizar equipe deste local"><i class="icon-user"></i></a>\
//                         <a href="#" class="btn btn-large pull-right btn-next" rel="tooltip" title="Entrar neste local"><i class="icon-circle-arrow-right"></i></a>\
//                       </div>\
//                     </li>\
//                     <li>\
//                       <a href="#" rel="tooltip" title="Escola Whatever The Hell they want to name this freaking school D">\
//                         <span class="link-text">Escola Whatever The Hell they want to name this freaking school D</span>\
//                         <div class="progress progress-warning pull-right">\
//                           <div class="bar" style="width: 30%;">\
//                             <span>80 de 220</span>\
//                           </div>\
//                         </div>\
//                       </a>\
//                       <div class="item-options clearfix">\
//                         <a href="#visualizarPessoas" data-toggle="modal" data-type="local" class="btn btn-large pull-left" rel="tooltip" title="Visualizar equipe deste local"><i class="icon-user"></i></a>\
//                         <a href="#" class="btn btn-large pull-right btn-next" rel="tooltip" title="Entrar neste local"><i class="icon-circle-arrow-right"></i></a>\
//                       </div>\
//                     </li>\
//                     <li>\
//                       <a href="#">\
//                         <span class="link-text">Escola E</span>\
//                         <div class="progress progress-danger pull-right">\
//                           <div class="bar" style="width: 10%;">\
//                             <span>22 de 220</span>\
//                           </div>\
//                         </div>\
//                       </a>\
//                       <div class="item-options clearfix">\
//                         <a href="#visualizarPessoas" data-toggle="modal" data-type="local" class="btn btn-large pull-left" rel="tooltip" title="Visualizar equipe deste local"><i class="icon-user"></i></a>\
//                         <a href="#" class="btn btn-large pull-right btn-next" rel="tooltip" title="Entrar neste local"><i class="icon-circle-arrow-right"></i></a>\
//                       </div>\
//                     </li>\
//                   </ul>';
//     $htmlSecaoTot = '<a href="#" class="btn btn-small pull-left btn-prev clearfix" rel="tooltip" title="Voltar para município"><i class="icon-circle-arrow-left"></i></a>\
//                   <a href="#" class="btn btn-small pull-right btn-divide clearfix" rel="tooltip" style="display:none" data-type="totalizacao" title="Não dividir por locais"><i class="icon-reorder"></i></a>\
//                   <a href="#" class="btn btn-small pull-right btn-divide clearfix not-divided" rel="tooltip" style="display:inline" data-type="totalizacao" title="Dividir por locais"><i class="icon-columns"></i></a>\
//                   <h3>\
//                     <span class="current-place-label">Município A</span>\
//                   </h3>\
//                   <div class="progress progress-success">\
//                     <div class="bar" style="width: 88%;">\
//                       <span>210 de 220</span>\
//                     </div>\
//                   </div>\
//                   <ul class="nav nav-pills nav-stacked has-item-options hover-inverse">\
//                     <li>\
//                       <a href="#">\
//                         <span class="link-text">Seção A - Local B</span>\
//                         <span class="label pull-right">não recebida</span>\
//                       </a>\
//                       <div class="item-options clearfix">\
//                         <a href="#visualizarPessoas" data-toggle="modal" data-type="secao" class="btn btn-large pull-left" rel="tooltip" title="Visualizar equipe desta seção"><i class="icon-user"></i></a>\
//                       </div>\
//                     </li>\
//                     <li>\
//                       <a href="#">\
//                         <span class="link-text">Seção B - Local A</span>\
//                         <span class="label pull-right">agregada</span>\
//                       </a>\
//                       <div class="item-options clearfix">\
//                         <a href="#visualizarPessoas" data-toggle="modal" data-type="secao" class="btn btn-large pull-left" rel="tooltip" title="Visualizar equipe desta seção"><i class="icon-user"></i></a>\
//                       </div>\
//                     </li>\
//                     <li>\
//                       <a href="#">\
//                         <span class="link-text">Seção C - Local B</span>\
//                         <span class="label pull-right">recebida</span>\
//                       </a>\
//                       <div class="item-options clearfix">\
//                         <a href="#visualizarPessoas" data-toggle="modal" data-type="secao" class="btn btn-large pull-left" rel="tooltip" title="Visualizar equipe desta seção"><i class="icon-user"></i></a>\
//                       </div>\
//                     </li>\
//                     <li>\
//                       <a href="#">\
//                         <span class="link-text">Seção D - Local B</span>\
//                         <span class="label pull-right">recebida</span>\
//                       </a>\
//                       <div class="item-options clearfix">\
//                         <a href="#visualizarPessoas" data-toggle="modal" data-type="secao" class="btn btn-large pull-left" rel="tooltip" title="Visualizar equipe desta seção"><i class="icon-user"></i></a>\
//                       </div>\
//                     </li>\
//                     <li>\
//                       <a href="#">\
//                         <span class="link-text">Seção E - Local C</span>\
//                         <span class="label pull-right">agregada</span>\
//                       </a>\
//                       <div class="item-options clearfix">\
//                         <a href="#visualizarPessoas" data-toggle="modal" data-type="secao" class="btn btn-large pull-left" rel="tooltip" title="Visualizar equipe desta seção"><i class="icon-user"></i></a>\
//                       </div>\
//                     </li>\
//                   </ul>';
//     $(this).parent().parent().parent().find(".loading").addClass("open");
//     if ($(this).hasClass("not-divided")) {
//       $(this).hide().prev().show();
//       setTimeout(function() {
//         $(_this).parent().parent().parent().find(".loading").removeClass("open");
//         if ($(_this).data("type") === "ocorrencia") {
//           return $(_this).parent().html($htmlSecao);
//         } else if ($(_this).data("type") === "totalizacao") {
//           return $(_this).parent().html($htmlLocal);
//         }
//       }, 500);
//     } else {
//       $(this).hide().next().show();
//       setTimeout(function() {
//         $(_this).parent().parent().parent().find(".loading").removeClass("open");
//         if ($(_this).data("type") === "ocorrencia") {
//           return $(_this).parent().html($htmlOcorrencia);
//         } else if ($(_this).data("type") === "totalizacao") {
//           return $(_this).parent().html($htmlSecaoTot);
//         }
//       }, 500);
//     }
//     $(this).tooltip("hide");
//     return e.preventDefault();
//   });

  /*
  Quando o usuário clicar no checkbox para marcar uma ocorrência como fechada ele terá o feedback no botão do formulário,
  onde o mesmo irá mudar de Enviar para Fechar ocorrência. O inverso irá acontecer quando o usuário desmarcar o checkbox.
  */


  $(".modal .operations .resolved").live("click", function() {
    if ($(this).attr("checked")) {
      $(this).parent().next().next().html("Fechar ocorrência");
      return $(this).parent().next().after('\
    <select class="input-small inline" id="solucao" style="margin: 0 25px 0 0;">\
      <option value="">Solução</option>\
      <option value="reiniciar_UE">reiniciar UE</option>\
      <option value="trocar_cartao_de_memoria">trocar cartão de memória</option>\
      <option value="troca_de_urna" data-solution="troca">troca de UE</option>\
    </select>');
    } else {
      $(this).parent().next().next().next().html("Enviar");
      return $(this).parent().next().next("#solucao").remove();
    }
  });

  /*
  Quando o usuário clicar no botão para bloquear um informante ele terá um feedback que:
  * irá exibir um alerta de confirmação para prosseguir ou não com o bloqueio do informate
  * se o usuário confirmar o bloqueio do informante o dado do informante irá ficar vermelho e ficar com um traço
    também irá mudar o botão de bloqueio para o botão de desbloqueio
  * se o usuário cancelar a operação de bloqueio nada será feito
  O inverso acontece quando o botão de desbloqueio estiver presente e for clicado.
  */


  $(".btn-block").live("click", function(e) {
    var blockString, continueBlock;
    blockString = $(this).hasClass("btn-danger") ? "bloquear" : "desbloquear";
    continueBlock = confirm("Tem certeza que deseja " + blockString + " este informante");
    if (continueBlock) {
      $(this).toggleClass("btn-danger").toggleClass("btn-success").prev(".inform").toggleClass("blocked");
      if ($(this).hasClass("btn-success")) {
        $(this).prev(".inform").html("<del>" + $(this).prev(".inform").html() + "</del>");
        $(this).html('<i class="icon-unlock"></i> desbloquear');
      } else {
        $(this).prev(".inform").html($(this).prev(".inform").children("del").html());
        $(this).html('<i class="icon-lock"></i> bloquear');
      }
    }
    return e.preventDefault();
  });

  /*
  Esta função é responsável pelos (micro)formulários AJAX dentro da visualização de ocorrências. Estes formulários são:
  * Delegar equipe
  * Problema de urna
  
  Esta função é ativada no clique dos botões:
  * delegar equipe
  * checkbox de problema de urna 
  * botão delegar dentro do fomulário de escolha de equipe
  * botão de modificar dentro do formulário de escolha de tipo de problema
  
  Esta função dá os seguintes feedbacks:
  * quando o usuário selecionar e submeter uma equipe, muda-se o valor da equipe atual para a equipe selecionada
  * quando o usuário selecionar e submeter um tipo de problema: 
    ** irá adicionar labels ao cabeçalho da modal window com o tipo do problema
       e com o número da urna (que deverá ser informado automaticamente pelo sistema)
    ** irá substituir o checkbox de tipo de problema por selects:
       *** com os tipos de problema, com o tipo de problema escolhido selecionado
       *** com os tipos de solução
  */


  $('.choose-mini-form .close, .open-mini-form, .close-mini-form').live("click", function(e) {
    var $current, $html, $selectedOP;
    if ($(this).hasClass("close-mini-form")) {
      $current = $(this).parent().parent().find(".current");
      if ($current.data("type") === "team" && $(this).parent().find('[class^="input-"]').val() !== "") {
        $current.children(".current-" + $current.data("type")).html($(this).parent().find('[class^="input-"]').val());
      }
      $html = '<select class="input-small" id="tipo-problema">\
                        <option value="">Tipo de problema</option>\
                        <option value="urna_nao_liga">urna não liga</option>\
                        <option value="urna_com_bateria_fraca">urna com bateria fraca</option>\
                      </select>\
                      <input class="ue-number" type="text" placeholder="número da urna de continncia" />';
      if ($current.data("type") === "problem" && $(this).parent().find('[class^="input-"]').val() !== "") {
        $(this).parent().parent().find(".current").html($html);
        $selectedOP = $(this).parent().find('[class^="input-"] option:selected');
        $(this).parent().parent().find(".current").children("#tipo-problema").find("option").each(function() {
          if ($(this).html() === $selectedOP.html()) {
            return $(this).attr("selected", "selected");
          }
        });
        $(this).parent().parent().parent().parent().find(".modal-header").append('<span class="label">' + $(this).parent().find('[class^="input-"] option:selected').html() + '</span> <span class="label">urna número: 0099887</span>');
      }
    }
    $(this).parent().parent().find(".hide").toggleClass("hide");
    $(this).parent().toggleClass("hide");
    return e.preventDefault();
  });

  /*
  Quando o usuário escolher um tipo de solução, e este tipo for troca de urna, irá aparecer um campo para o usuário
  informar o número da urna de contingência.
  */


  $("#solucao").live("change", function() {
    if ($("#solucao option:selected").data("solution") === "troca") {
      return $(this).next(".ue-number").addClass("show");
    } else {
      return $(this).next(".ue-number").removeClass("show");
    }
  });

  /*
  Este código é responsável pela abertura da modal de visualização de pessoas.
  Ela é utilizada pelas widgets de transmissão, ocorrência e totalização.
  De acordo com o nível, ou 'página', que o usuário estiver na widget a modal irá exibir um conteúdo diferente,
  que deverá ser carregado via AJAX (aqui simulado pelas variáveis $htmlTransmissao, $htmlSecao, $htmlLocal e $htmlMunicipio).
  Os titulos da modal também irá variar de acordo com o item clicado, no caso da widget de local de transmissão o título também irá
  conter o status (online/offline + H/N/A/L).
  A verificação de qual o nível, ou 'página' que a widget está sendo chamada é feita pelo atributo data-type.
  */


  $('[href="#visualizarPessoas"]').live("click", function() {
    var $htmlLocal, $htmlMunicipio, $htmlSecao, $htmlTransmissao;
    $htmlTransmissao = '<h4>Técnicos de transmissão</h4><br />\
                  <table class="table table-striped table-bordered">\
                    <thead>\
                      <tr>\
                        <th>Nome</th>\
                        <th>Telefone</th>\
                      </tr>\
                    </thead>\
                    <tbody>\
                      <tr>\
                        <td>José Silvestre</td>\
                        <td>9999-8888</td>\
                      </tr>\
                      <tr>\
                        <td>Creuza Pereira</td>\
                        <td>9898-8989</td>\
                      </tr>\
                    </tbody>\
                  </table>';
    $htmlSecao = '<h4>Mesários</h4><br />\
                  <table class="table table-striped table-bordered">\
                    <thead>\
                      <tr>\
                        <th>Nome</th>\
                        <th>Telefone</th>\
                        <th>Função</th>\
                      </tr>\
                    </thead>\
                    <tbody>\
                      <tr>\
                        <td>José Silvestre</td>\
                        <td>9999-8888</td>\
                        <td>primeiro mesário</td>\
                      </tr>\
                      <tr>\
                        <td>Creuza Pereira</td>\
                        <td>9898-8989</td>\
                        <td>chefe de seção</td>\
                      </tr>\
                    </tbody>\
                  </table>';
    $htmlLocal = '<h4>Equipe X</h4><br />\
                  <table class="table table-striped table-bordered">\
                    <thead>\
                      <tr>\
                        <th>Nome</th>\
                        <th>Telefone</th>\
                        <th>Função</th>\
                      </tr>\
                    </thead>\
                    <tbody>\
                      <tr>\
                        <td>José Silvestre</td>\
                        <td>9999-8888</td>\
                        <td>técnico de urna</td>\
                      </tr>\
                      <tr>\
                        <td>Creuza Pereira</td>\
                        <td>9898-8989</td>\
                        <td>técnico de urna</td>\
                      </tr>\
                    </tbody>\
                  </table>';
    $htmlMunicipio = '<h4>Escola A - Equipe X</h4><br />\
                  <table class="table table-striped table-bordered">\
                    <thead>\
                      <tr>\
                        <th>Nome</th>\
                        <th>Telefone</th>\
                        <th>Função</th>\
                      </tr>\
                    </thead>\
                    <tbody>\
                      <tr>\
                        <td>José Silvestre</td>\
                        <td>9999-8888</td>\
                        <td>técnico de urna</td>\
                      </tr>\
                      <tr>\
                        <td>Creuza Pereira</td>\
                        <td>9898-8989</td>\
                        <td>técnico de urna</td>\
                      </tr>\
                    </tbody>\
                  </table>\
\
                  <h4>Escola B - Equipe Y</h4><br />\
                  <table class="table table-striped table-bordered">\
                    <thead>\
                      <tr>\
                        <th>Nome</th>\
                        <th>Telefone</th>\
                        <th>Função</th>\
                      </tr>\
                    </thead>\
                    <tbody>\
                      <tr>\
                        <td>Carlos da Silva</td>\
                        <td>9999-8888</td>\
                        <td>técnico de urna</td>\
                      </tr>\
                      <tr>\
                        <td>João de Nóbrega</td>\
                        <td>9898-8989</td>\
                        <td>técnico de urna</td>\
                      </tr>\
                    </tbody>\
                  </table>';
    if ($(this).data("type") === "secao") {
      $("#visualizarPessoas").find(".modal-header h3").html("Escola A - Seção X");
      return $("#visualizarPessoas").find(".modal-body").html($htmlSecao);
    } else if ($(this).data("type") === "local") {
      $("#visualizarPessoas").find(".modal-header h3").html("Escola A");
      return $("#visualizarPessoas").find(".modal-body").html($htmlLocal);
    } else if ($(this).data("type") === "municipio") {
      $("#visualizarPessoas").find(".modal-header h3").html("Município A");
      return $("#visualizarPessoas").find(".modal-body").html($htmlMunicipio);
    } else if ($(this).data("type") === "transmissao") {
      $("#visualizarPessoas").find(".modal-header h3").html('<span class="label label-success" rel="tooltip" title="Aguardando">A</span>\
    014 - Palmas - Colégio Doc Emmett Brown');
      return $("#visualizarPessoas").find(".modal-body").html($htmlTransmissao);
    }
  });

  /*
  Quando o usuário for um técnico de transmissão, o sistema irá exibir um botão no topo para o técnico homologar o local.
  Que quando homologado irá adicionar a classe sucesso e modificar o texto do botão para Ponto homologado, desabilitando o botão.
  */


  $(".btn-homologar").live("click", function() {
    return $("#confirmacaoHomologacao").modal("toggle");
  });

  $("#confirmacaoHomologacao .modal-footer a").on("click", function() {
    return $(".btn-homologar").attr("disabled", "true").addClass("btn-success").html("Ponto homologado");
  });

  /*
  Na widget de mensagens, o formulário contendo os campos irá exibir apenas o textarea inicialmente.
  Porém, quando este textarea entrar em foco, o sistema irá exibir os outros campos, adicionando a classe visible para
  os campos inicialmente escondidos e retracted para o textarea e #messages para o formulário ficar com a exibição mais homogênea.
  */


  $("#message-form form textarea").on("focus", function() {
    $(this).addClass("retracted");
    $(this).parents("form").find(".as-selections, button").addClass("visible");
    return $(this).parents("#sidebar").find("#messages").addClass("retracted");
  });

  /*
  Quando o usuário submeter a mensagem, na widget de mensagens, o formulário irá voltar para seu estado inicial,
  com apenas o campo textarea exibido. O script também irá limpar todos os dados do formulário.
  Ao final do envio da mensagem, irá ser exibido um alerta como forma de feedback para o usuário.
  */


  $("#message-form form button").on("click", function(e) {
    $(this).parents("form").find("textarea").removeClass("retracted").val("");
    $(this).parents("form").find(".as-selections, button").removeClass("visible");
    $(this).parents("#sidebar").find("#messages").removeClass("retracted");
    $(this).parents("form").find(".as-selection-item").remove();
    $(this).parents("form").find(".as-values").val("");
    $(this).parents(".container").prepend('<div class="alert alert-success hide" style="position:fixed; top:47px; left:97px; z-index: 10009">\
      <button class="close" data-dismiss="alert">×</button>\
      Sua mensagem foi enviada com sucesso\
    </div>');
    $(this).parents(".container").find(".alert").slideToggle('fast');
    return e.preventDefault();
  });

  /*
  Para simular o envio com ajax, o submit do form irá receber false para não recarregar a página.
  */


  $("#message-form form").on("submit", function() {
    return false;
  });

  /*
  Ao final de toda operação irá ser exibido um alerta para o usuário como forma de feedback, já que todas as operações
  do sistema são feitas com AJAX.
  */


  $(".modal .modal-footer .btn-primary, .modal .modal-footer .btn-danger").on("click", function() {
    var $current, mensagem;
    $(this).parents(".container").find(".alert").slideToggle('fast').remove();
    mensagem = "";
    $current = $(this).parents(".modal");
    if ($current.attr("id") === "cadastrarOcorrencia") {
      mensagem = "Ocorrência cadastrada com sucesso";
    } else if ($current.attr("id") === "cadastrarOcorrenciaCorregedoria") {
      mensagem = "Ocorrência para corregedoria cadastrada com sucesso";
    } else if ($current.attr("id") === "revogarPonto") {
      mensagem = "Local de transmissão revogado com sucesso";
    }
    $(this).parents(".container").prepend("<div class=\"alert alert-success hide\" style=\"position:fixed; top:47px; left:97px; z-index: 10009\">      <button class=\"close\" data-dismiss=\"alert\">×</button>      " + mensagem + "    </div>");
    return $(this).parents(".container").find(".alert").slideToggle('fast');
  });

  /*
  Quando o sistema estiver sendo exibido num tablet ou em um desktop com monitor entre 800x600/1024x768 o layout irá mudar para exibir
  apenas 1 widget por vez e haverá também navegação/paginação entre widgets.
  Para isto o elemento mobile-widgets-nav foi criado e os links deles irão ser usados para navegar entre as widgets de forma parecida
  com a navegação entre as páginas de uma widget.
  */


  $("#mobile-widgets-nav a").live("click", function(e) {
    if ($(this).hasClass("btn-next")) {
      $("#mobile-widgets-nav .btn-prev").removeClass("disabled");
      if (!$(this).hasClass("disabled")) {
        if (!$(this).parents(".widgets").find('[class^="widget-"].current').hasClass("widget-ocorrencia")) {
          $(this).parents(".widgets").find('[class^="widget-"].current').removeClass("current").addClass("past").next().addClass("current");
        } else {
          $(this).parents(".widgets").find('[class^="widget-"].current').removeClass("current").addClass("past").parent().next().find(".widget-totalizacao").addClass("current");
        }
        $(this).parents("#mobile-widgets-nav").find("#pages .current").removeClass("current").next().addClass("current");
        if ($(this).parents(".widgets").find('[class^="widget-"].current').hasClass("widget-corregedoria")) {
          $(this).addClass("disabled");
        }
      }
    } else if ($(this).hasClass("btn-prev")) {
      $("#mobile-widgets-nav .btn-next").removeClass("disabled");
      if (!$(this).hasClass("disabled")) {
        if (!$(this).parents(".widgets").find('[class^="widget-"].current').hasClass("widget-totalizacao")) {
          $(this).parents(".widgets").find('[class^="widget-"].current').removeClass("current").prev().removeClass("past").addClass("current");
        } else {
          $(this).parents(".widgets").find('[class^="widget-"].current').removeClass("current").parent().prev().find(".widget-ocorrencia").removeClass("past").addClass("current");
        }
        $(this).parents("#mobile-widgets-nav").find("#pages .current").removeClass("current").prev().addClass("current");
        if ($(this).parents(".widgets").find('[class^="widget-"].current').hasClass("widget-transmissao")) {
          $(this).addClass("disabled");
        }
      }
    }
    return e.preventDefault();
  });

  /*
  Quando o botão para esconder a barra lateral, contendo a widget de mensagens, for clicado:
  Esta será retraída (adicionando a classe .retracted), o ícone do botão irá mudar para indicar
  que agora ele irá expandir a sidebar e a div .widgets irá ser expandida, adicionando a classe .expanded.
  */


  $("#sidebar-toggle a").on("click", function(e) {
    $(this).parent().toggleClass("nl");
    $(this).parent().parent().find("#sidebar").toggleClass("retracted");
    if ($(this).parent().hasClass("nl")) {
      $(this).html('<i class="icon-comment"></i> <i class="icon-caret-right"></i>');
    } else {
      $(this).html('<i class="icon-caret-left"></i> <i class="icon-comment-alt"></i>');
    }
    return $(this).parents(".row").find(".widgets").toggleClass("expanded");
  });

  /*
  Irá substituir os checkboxes e radio buttons por switches
  */


  $('input[type=radio].mini-switch, input[type=checkbox].mini-switch').hide().after('<span class="mini-switch-replace"></span>');

}).call(this);
