// Generated by CoffeeScript 1.4.0
/*
creates the subnav fixation effect.
*/

var $nav, $win, data, isFixed, navTop, processScroll;

$win = $(window);

$nav = $('.subnav');

navTop = $('.subnav').length && $('.subnav').offset().top - 40;

isFixed = 0;

processScroll = function() {
  var i, scrollTop;
  i = 0;
  scrollTop = $win.scrollTop();
  if (scrollTop >= navTop && !isFixed) {
    isFixed = 1;
    return $nav.addClass('subnav-fixed');
  } else if (scrollTop <= navTop && isFixed) {
    isFixed = 0;
    return $nav.removeClass('subnav-fixed');
  }
};

processScroll();

$win.on('scroll', processScroll);

/*
Add the 'expand' feature to the widgets.
When the button is clicked the .expanded class will be added to the targeted widgtet.
*/


$(".expander").on("click", function(e) {
  $(this).parents('[class^="widget-"]').toggleClass("expanded");
  return e.preventDefault();
});

/*
Add the configuration pannel to the widgets.
When the button is clicked the .open class will be added to the settings pannel, and with that, making it visible.
*/


$(".settings-nub").on("click", function(e) {
  $(this).toggleClass("open").parent().parent().find(".settings").toggleClass("open");
  return e.preventDefault();
});

/*
Close the configurations pannel when the filter button is clicked.
*/


$(".settings button").on("click", function(e) {
  if ($(this).hasClass("btn-filtro")) {
    $(this).parent().parent().parent().find(".settings-nub, .settings").toggleClass("open");
  }
  return e.preventDefault();
});

/*
ADd the tooltip initializer, using the bootstrap's native plugin.
*/


$("[rel='tooltip']").tooltip();

/*
Add the autocomplete feature to the elements with the .chosen class.
This autocomplete DOES NOT feature AJAX calls, it mounts the autocompletion based on the list itens of a ul or select elements.
The chosen plugin is at js/chosen.jquery.min.js
*/


$(".chosen").chosen({
  no_results_text: "No result found"
});

/*
Making some bootstrap data to be used on the AJAX autocomplete.
*/


data = {
  items: [
    {
      value: "21",
      name: "A item"
    }, {
      value: "43",
      name: "Another item"
    }, {
      value: "46",
      name: "Some other fake item"
    }, {
      value: "54",
      name: "Yet another fake item"
    }
  ]
};

/*
Adds the AJAX autocomplete feature, with multiple selections, to the elements with the .autocomplete class and to the #message-form input on the messages widget.
This code uses the AutoSuggest plugin, it is at js/jquery.autosugest.min.js
*/


$(".autocomplete").autoSuggest(data.items, {
  selectedItemProp: "name",
  searchObjProps: "name",
  startText: "Add filter",
  emptyText: "No results",
  limitText: "You can't make another selection",
  minChars: 2,
  selectionLimit: 3
});

$("#message-form input").autoSuggest(data.items, {
  selectedItemProp: "name",
  searchObjProps: "name",
  startText: "Send to",
  emptyText: "No results",
  limitText: "You can't make another selection",
  minChars: 2,
  selectionLimit: 3
});

/*
Add the focus/blur effect to the autocomplete, to mimmic the native bootstrap look.
*/


$(".as-selections input").focus(function() {
  return $(this).parent().parent().addClass("focus");
}).blur(function() {
  return $(this).parent().parent().removeClass("focus");
});

/*
Add the single item autocomplete, with ajax, feature, targeted to the mun-autocomplete class.
This code uses the bootstrap.typeahead that is included on the js/bootstrap.min.js file.
*/


$(".mun-autocomplete").typeahead({
  source: ['A place', 'Another place', 'Some other place']
});

/*
Add the online/offline filter feature to the first widget.
When one of the filter buttons is clicked, it will add the .active class to the clicked button and the elements with the data-trans-status not equal to it's data-trans-status will be hidden.
*/


$('[class^="widget-"] > .form-actions > .btn').on("click", function(e) {
  var $button;
  if ($(this).data("toggle") === "button") {
    $(this).removeClass("transparent");
    $(this).next().toggleClass("transparent");
    $(this).prev().toggleClass("transparent");
    if ($(this).next(".btn").hasClass("active")) {
      $(this).next(".btn").button("toggle");
    }
    if ($(this).prev(".btn").hasClass("active")) {
      $(this).prev(".btn").button("toggle");
    }
  }
  $button = $(this);
  $(this).parent().next().children().children("li").each(function() {
    if ($(this).data("trans-status") === $button.data("trans-status")) {
      return $(this).show();
    } else if (($(this).data("trans-status") !== $button.data("trans-status")) && ($button.hasClass("active"))) {
      return $(this).show();
    } else {
      return $(this).hide();
    }
  });
  return e.preventDefault();
});

/*
Expands the options to the items that has the .has-item-options class.
*/


$(".code-wrap .has-item-options li > a").live("click", function(e) {
  $(this).next(".item-options").slideToggle("fast");
  $(this).parent("li").has(".item-options").toggleClass("active");
  return e.preventDefault();
});

/*
When a button on the expanded pannel of the itens is clicked, the expanded pannel is closed to mimmic a performed action.
*/


$(".option-open, .option-close").live("click", function(e) {
  $(this).parent().slideUp("fast");
  $(this).parent().parent("li").toggleClass("active");
  return e.preventDefault();
});

/*
Add the 'level navigation' feature to the widgets.
This widget simulates a AJAX call, of the next level's items, with the setTimeout function. 
To this concept, the initial code of the next level would already be present on the 'final' HTML
with the #step-x id, being 'x' the pagination number that the level will be. Only the content would be loaded via an AJAX call.
eg.:

<div class='content-wrap'>
  <div class='step-1 current'>
    <!-- visible div on the screen -->
  </div>
  <div class='step-2'>
   <!-- hidden div, that will have it's content loaded via AJAX -->
  </div>
  <div class='step-3'>
   <!-- hidden div, that will have it's content loaded via AJAX -->
  </div>
  ...
</div>

With a real AJAX call, after the call of the $(this).parents('[class^="widget-"]').find(".loading").addClass("open") part,
on the method's success event the final HTML with the content would be injected as response a the div $('.step-x').next('.step-x+1').html($meuHTMLdeResposta).
Following that, the procedures that are executed at the setTimeout function are trigged to animate and hide the pannel with the loading indicator.

The HTML formatting must be as the example above, and the one found at the HTML.
*/


$(".btn-next").live("click", function(e) {
  var _this = this;
  $(this).parents('[class^="widget-"]').find(".loading").addClass("open");
  setTimeout(function() {
    $(_this).parents('[class^="step-"]').removeClass("current").addClass("past").next().addClass("current");
    $(_this).parents('[class^="widget-"]').find(".loading").removeClass("open");
    return $(_this).removeClass("current-clicked");
  }, 500);
  return e.preventDefault();
});

/*
Add the 'back to the previous level' feature to the widgets that have the 'level navigation'.
To return to the previous level there is no AJAX call. Just straight up DOM manipulation and visual effects. Because the previous page is 'hidden' at the left of the current page. 
The current page will be marked with the .current class, and the pages that where active will be marked with the .past class.
The 'next' levels don't need any other class that is not the .step-x class.
ex.:

<div class='content-wrap'>
  <div class='step-1 past'>
    <!-- hidden div, that has the populated DOM -->
  </div>
  <div class='step-2 past'>
    <!-- hidden div, that has the populated DOM -->
  </div>
  <div class='step-3 current'>
    <!-- currently visible div on the screen -->
  </div>
  <div class='step-4'>
    <!-- hidden div, that will have it's content loaded via AJAX -->
  </div>
  ...
</div>
*/


$(".btn-prev").live("click", function(e) {
  $(this).parent().removeClass("current").prev().addClass("current").removeClass("past");
  return e.preventDefault();
});

/*
Add the 'toggle view mode' to the widgets.
This method mimmics the injection of HTML ($htmlOcorrencia, $htmlSecao, $$htmlLocal e $htmlSecaoTot) from a AJAX call.
This function is used by the two states of the view mode.
*/


$(".btn-divide").live("click", function(e) {
  var $htmlLocal, $htmlOcorrencia, $htmlSecao, $htmlSecaoTot,
    _this = this;
  $htmlOcorrencia = '<a href="#" class="btn btn-small pull-left btn-prev clearfix" rel="tooltip" title="Back"><i class="icon-circle-arrow-left"></i></a>\
                  <a href="#" class="btn btn-small pull-right btn-divide clearfix" data-type="ocorrencia" style="display:none" rel="tooltip" title="toggle view mode"><i class="icon-reorder"></i></a>\
                  <a href="#" class="btn btn-small pull-right btn-divide clearfix not-divided" data-type="ocorrencia" style="display:inline" rel="tooltip" title="toggle view mode"><i class="icon-columns"></i></a>\
                  <h3>\
                    The visualization has changed!\
                    <span class="current-place-label">Item Whatever The Hell they want to name this freaking school D</span>\
                  </h3>\
                  <ul class="nav nav-pills nav-stacked hover-inverse">\
                    <li>\
                      <a href="#visualizarOcorrencia" data-toggle="modal">\
                        <span class="label label-icon" rel="tooltip" title="a label"><i class="icon-check-empty"></i></span>\
                        <span class="link-text">Item A</span>\
                        <span class="badge pull-right">23ª</span>\
                      </a>\
                    </li>\
                    <li class="falta-mesario">\
                      <a href="#visualizarOcorrencia" data-toggle="modal">\
                        <span class="label label-icon" rel="tooltip" title="another label"><i class="icon-check"></i></span>\
                        <span class="link-text"><del>Item B</del></span>\
                        <span class="badge pull-right">24ª</span>\
                        <span class="label pull-right">a label</span>\
                      </a>\
                    </li>\
                    <li>\
                      <a href="#visualizarOcorrencia" data-toggle="modal">\
                        <span class="label label-icon" rel="tooltip" title="another label"><i class="icon-check"></i></span>\
                        <span class="link-text"><del>Item C</del></span>\
                        <span class="badge pull-right">21ª</span>\
                      </a>\
                    </li>\
                    <li class="parada">\
                      <a href="#visualizarOcorrencia" data-toggle="modal">\
                        <span class="label label-icon" rel="tooltip" title="a label"><i class="icon-check-empty"></i></span>\
                        <span class="link-text">Item D</span>\
                        <span class="badge pull-right">21ª</span>\
                        <span class="label pull-right">another label</span>\
                      </a>\
                    </li>\
                    <li>\
                      <a href="#visualizarOcorrencia" data-toggle="modal">\
                        <span class="label label-icon" rel="tooltip" title="a label"><i class="icon-check-empty"></i></span>\
                        <span class="link-text">Item E</span>\
                        <span class="badge pull-right">23ª</span>\
                      </a>\
                    </li>\
                  </ul>\
                  <a href="#" class="btn btn-large btn-load-more">Load more</a>\
\
                  <script type="text/javascript">\
                    $("[rel=\'tooltip\']").tooltip();\
                  </script>';
  $htmlSecao = '<a href="#" class="btn btn-small pull-left btn-prev clearfix" rel="tooltip" title="Back"><i class="icon-circle-arrow-left"></i></a>\
                  <a href="#" class="btn btn-small pull-right btn-divide clearfix" rel="tooltip" data-type="ocorrencia" title="toggle view mode"><i class="icon-reorder"></i></a>\
                  <a href="#" class="btn btn-small pull-right btn-divide clearfix not-divided" data-type="ocorrencia" rel="tooltip" title="toggle view mode"><i class="icon-columns"></i></a>\
                  <h3>\
                    Yay! Changed the view mode\
                    <span class="current-place-label">Item Whatever The Hell they want to name this freaking school D</span>\
                  </h3>\
                  <ul class="nav nav-pills nav-stacked has-item-options hover-inverse">\
                    <li>\
                      <a href="#">\
                        <span class="link-text">Item A</span>\
                        <span class="badge pull-right">13</span>\
                      </a>\
                      <div class="item-options clearfix">\
                        <a href="#cadastrarOcorrencia" data-toggle="modal" class="btn btn-large pull-left" rel="tooltip" title="Add something here"><i class="icon-plus"></i></a>\
                        <a href="#visualizarPessoas" data-toggle="modal" data-type="secao" class="btn btn-large user-list" rel="tooltip" title="View some data from this item"><i class="icon-user"></i></a>\
                        <a href="#" class="btn btn-large pull-right btn-next" rel="tooltip" title="Enter this level"><i class="icon-circle-arrow-right"></i></a>\
                      </div>\
                    </li>\
                    <li class="falta-mesario">\
                      <a href="#">\
                        <span class="link-text">Item B</span>\
                        <span class="badge pull-right">21</span>\
                        <span class="label pull-right">a label</span>\
                      </a>\
                      <div class="item-options clearfix">\
                        <a href="#cadastrarOcorrencia" data-toggle="modal" class="btn btn-large pull-left" rel="tooltip" title="Add something here"><i class="icon-plus"></i></a>\
                        <a href="#visualizarPessoas" data-toggle="modal" data-type="secao" class="btn btn-large user-list" rel="tooltip" title="View some data from this item"><i class="icon-user"></i></a>\
                        <a href="#" class="btn btn-large pull-right btn-next" rel="tooltip" title="Enter this level"><i class="icon-circle-arrow-right"></i></a>\
                      </div>\
                    </li>\
                    <li>\
                      <a href="#">\
                        <span class="link-text">Item C</span>\
                        <span class="badge pull-right">31</span>\
                      </a>\
                      <div class="item-options clearfix">\
                        <a href="#cadastrarOcorrencia" data-toggle="modal" class="btn btn-large pull-left" rel="tooltip" title="Add something here"><i class="icon-plus"></i></a>\
                        <a href="#visualizarPessoas" data-toggle="modal" data-type="secao" class="btn btn-large user-list" rel="tooltip" title="View some data from this item"><i class="icon-user"></i></a>\
                        <a href="#" class="btn btn-large pull-right btn-next" rel="tooltip" title="Enter this level"><i class="icon-circle-arrow-right"></i></a>\
                      </div>\
                    </li>\
                    <li class="parada">\
                      <a href="#">\
                        <span class="link-text">Item D</span>\
                        <span class="badge pull-right">18</span>\
                        <span class="label pull-right">another label</span>\
                      </a>\
                      <div class="item-options clearfix">\
                        <a href="#cadastrarOcorrencia" data-toggle="modal" class="btn btn-large pull-left" rel="tooltip" title="Add something here"><i class="icon-plus"></i></a>\
                        <a href="#visualizarPessoas" data-toggle="modal" data-type="secao" class="btn btn-large user-list" rel="tooltip" title="View some data from this item"><i class="icon-user"></i></a>\
                        <a href="#" class="btn btn-large pull-right btn-next" rel="tooltip" title="Enter this level"><i class="icon-circle-arrow-right"></i></a>\
                      </div>\
                    </li>\
                    <li>\
                      <a href="#">\
                        <span class="link-text">Item E</span>\
                        <span class="badge pull-right">1</span>\
                      </a>\
                      <div class="item-options clearfix">\
                        <a href="#cadastrarOcorrencia" data-toggle="modal" class="btn btn-large pull-left" rel="tooltip" title="Add something here"><i class="icon-plus"></i></a>\
                        <a href="#visualizarPessoas" data-toggle="modal" data-type="secao" class="btn btn-large user-list" rel="tooltip" title="View some data from this item"><i class="icon-user"></i></a>\
                        <a href="#" class="btn btn-large pull-right btn-next" rel="tooltip" title="Enter this level"><i class="icon-circle-arrow-right"></i></a>\
                      </div>\
                    </li>\
                  </ul>\
\
                  <script type="text/javascript">\
                    $("[rel=\'tooltip\']").tooltip();\
                  </script>';
  $htmlLocal = '<a href="#" class="btn btn-small pull-left btn-prev clearfix" rel="tooltip" title="Back"><i class="icon-circle-arrow-left"></i></a>\
                  <a href="#" class="btn btn-small pull-right btn-divide clearfix" rel="tooltip" data-type="totalizacao" title="toggle view mode"><i class="icon-reorder"></i></a>\
                  <a href="#" class="btn btn-small pull-right btn-divide clearfix not-divided" rel="tooltip" data-type="totalizacao" title="toggle view mode"><i class="icon-columns"></i></a>\
                  <h3>\
                    The view mode changed, hooray!\
                    <span class="current-place-label">Item A</span>\
                  </h3>\
                  <ul class="nav nav-pills nav-stacked has-item-options hover-inverse">\
                    <li>\
                      <a href="#">\
                        <span class="link-text">Item A</span>\
                        <div class="progress progress-info pull-right">\
                          <div class="bar" style="width: 60%;">\
                            <span>120 of 220</span>\
                          </div>\
                        </div>\
                      </a>\
                      <div class="item-options clearfix">\
                        <a href="#visualizarPessoas" data-toggle="modal" data-type="local" class="btn btn-large pull-left" rel="tooltip" title="View some data from this item"><i class="icon-user"></i></a>\
                        <a href="#" class="btn btn-large pull-right btn-next" rel="tooltip" title="Enter this level"><i class="icon-circle-arrow-right"></i></a>\
                      </div>\
                    </li>\
                    <li>\
                      <a href="#">\
                        <span class="link-text">Item B</span>\
                        <div class="progress progress-success pull-right">\
                          <div class="bar" style="width: 80%;">\
                            <span>200 of 220</span>\
                          </div>\
                        </div>\
                      </a>\
                      <div class="item-options clearfix">\
                        <a href="#visualizarPessoas" data-toggle="modal" data-type="local" class="btn btn-large pull-left" rel="tooltip" title="View some data from this item"><i class="icon-user"></i></a>\
                        <a href="#" class="btn btn-large pull-right btn-next" rel="tooltip" title="Enter this level"><i class="icon-circle-arrow-right"></i></a>\
                      </div>\
                    </li>\
                    <li>\
                      <a href="#">\
                        <span class="link-text">Item C</span>\
                        <div class="progress progress-info pull-right">\
                          <div class="bar" style="width: 60%;">\
                            <span>120 of 220</span>\
                          </div>\
                        </div>\
                      </a>\
                      <div class="item-options clearfix">\
                        <a href="#visualizarPessoas" data-toggle="modal" data-type="local" class="btn btn-large pull-left" rel="tooltip" title="View some data from this item"><i class="icon-user"></i></a>\
                        <a href="#" class="btn btn-large pull-right btn-next" rel="tooltip" title="Enter this level"><i class="icon-circle-arrow-right"></i></a>\
                      </div>\
                    </li>\
                    <li>\
                      <a href="#" rel="tooltip" title="Item Whatever The Hell they want to name this freaking school D">\
                        <span class="link-text">Item Whatever The Hell they want to name this freaking school D</span>\
                        <div class="progress progress-warning pull-right">\
                          <div class="bar" style="width: 30%;">\
                            <span>80 of 220</span>\
                          </div>\
                        </div>\
                      </a>\
                      <div class="item-options clearfix">\
                        <a href="#visualizarPessoas" data-toggle="modal" data-type="local" class="btn btn-large pull-left" rel="tooltip" title="View some data from this item"><i class="icon-user"></i></a>\
                        <a href="#" class="btn btn-large pull-right btn-next" rel="tooltip" title="Enter this level"><i class="icon-circle-arrow-right"></i></a>\
                      </div>\
                    </li>\
                    <li>\
                      <a href="#">\
                        <span class="link-text">Item E</span>\
                        <div class="progress progress-danger pull-right">\
                          <div class="bar" style="width: 10%;">\
                            <span>22 of 220</span>\
                          </div>\
                        </div>\
                      </a>\
                      <div class="item-options clearfix">\
                        <a href="#visualizarPessoas" data-toggle="modal" data-type="local" class="btn btn-large pull-left" rel="tooltip" title="View some data from this item"><i class="icon-user"></i></a>\
                        <a href="#" class="btn btn-large pull-right btn-next" rel="tooltip" title="Enter this level"><i class="icon-circle-arrow-right"></i></a>\
                      </div>\
                    </li>\
                  </ul>';
  $htmlSecaoTot = '<a href="#" class="btn btn-small pull-left btn-prev clearfix" rel="tooltip" title="Back"><i class="icon-circle-arrow-left"></i></a>\
                  <a href="#" class="btn btn-small pull-right btn-divide clearfix" rel="tooltip" style="display:none" data-type="totalizacao" title="toggle view mode"><i class="icon-reorder"></i></a>\
                  <a href="#" class="btn btn-small pull-right btn-divide clearfix not-divided" rel="tooltip" style="display:inline" data-type="totalizacao" title="toggle view mode"><i class="icon-columns"></i></a>\
                  <h3>\
                    <span class="current-place-label">You just changed the view mode!</span>\
                  </h3>\
                  <div class="progress progress-success">\
                    <div class="bar" style="width: 88%;">\
                      <span>210 of 220</span>\
                    </div>\
                  </div>\
                  <ul class="nav nav-pills nav-stacked has-item-options hover-inverse">\
                    <li>\
                      <a href="#">\
                        <span class="link-text">Item A - Local B</span>\
                        <span class="label pull-right">some label</span>\
                      </a>\
                      <div class="item-options clearfix">\
                        <a href="#visualizarPessoas" data-toggle="modal" data-type="secao" class="btn btn-large pull-left" rel="tooltip" title="View some data from this item"><i class="icon-user"></i></a>\
                      </div>\
                    </li>\
                    <li>\
                      <a href="#">\
                        <span class="link-text">Item B - Local A</span>\
                        <span class="label pull-right">other label</span>\
                      </a>\
                      <div class="item-options clearfix">\
                        <a href="#visualizarPessoas" data-toggle="modal" data-type="secao" class="btn btn-large pull-left" rel="tooltip" title="View some data from this item"><i class="icon-user"></i></a>\
                      </div>\
                    </li>\
                    <li>\
                      <a href="#">\
                        <span class="link-text">Item C - Local B</span>\
                        <span class="label pull-right">another label</span>\
                      </a>\
                      <div class="item-options clearfix">\
                        <a href="#visualizarPessoas" data-toggle="modal" data-type="secao" class="btn btn-large pull-left" rel="tooltip" title="View some data from this item"><i class="icon-user"></i></a>\
                      </div>\
                    </li>\
                    <li>\
                      <a href="#">\
                        <span class="link-text">Item D - Local B</span>\
                        <span class="label pull-right">another label</span>\
                      </a>\
                      <div class="item-options clearfix">\
                        <a href="#visualizarPessoas" data-toggle="modal" data-type="secao" class="btn btn-large pull-left" rel="tooltip" title="View some data from this item"><i class="icon-user"></i></a>\
                      </div>\
                    </li>\
                    <li>\
                      <a href="#">\
                        <span class="link-text">Item E - Local C</span>\
                        <span class="label pull-right">other label</span>\
                      </a>\
                      <div class="item-options clearfix">\
                        <a href="#visualizarPessoas" data-toggle="modal" data-type="secao" class="btn btn-large pull-left" rel="tooltip" title="View some data from this item"><i class="icon-user"></i></a>\
                      </div>\
                    </li>\
                  </ul>';
  $(this).parent().parent().parent().find(".loading").addClass("open");
  if ($(this).hasClass("not-divided")) {
    $(this).hide().prev().show();
    setTimeout(function() {
      $(_this).parent().parent().parent().find(".loading").removeClass("open");
      if ($(_this).data("type") === "ocorrencia") {
        return $(_this).parent().html($htmlSecao);
      } else if ($(_this).data("type") === "totalizacao") {
        return $(_this).parent().html($htmlLocal);
      }
    }, 500);
  } else {
    $(this).hide().next().show();
    setTimeout(function() {
      $(_this).parent().parent().parent().find(".loading").removeClass("open");
      if ($(_this).data("type") === "ocorrencia") {
        return $(_this).parent().html($htmlOcorrencia);
      } else if ($(_this).data("type") === "totalizacao") {
        return $(_this).parent().html($htmlSecaoTot);
      }
    }, 500);
  }
  $(this).tooltip("hide");
  return e.preventDefault();
});

/*
This is the function to simulate multiple actions on the form of the second widget. Just add/remove some extra options when the checkboxes are toggled.
*/


$(".modal .operations .resolved").live("click", function() {
  if ($(this).attr("checked")) {
    $(this).parent().next().next().html("Change the status");
    return $(this).parent().next().after('\
    <select class="input-small inline" id="solucao" style="margin: 0 25px 0 0;">\
      <option value="">Select one</option>\
      <option value="reiniciar_UE">another status</option>\
      <option value="trocar_cartao_de_memoria">never mind</option>\
      <option value="troca_de_urna" data-solution="troca">other good status</option>\
    </select>');
  } else {
    $(this).parent().next().next().next().html("Save");
    return $(this).parent().next().next("#solucao").remove();
  }
});

$(".modal .operations .duplicated").live("click", function() {
  if ($(this).attr("checked")) {
    return $(this).parent().next().html("A different action");
  } else {
    return $(this).parent().next().html("Save");
  }
});

/*
Mimmics a blocking action on the modal window visualzation of the second widget.
*/


$(".btn-block").live("click", function(e) {
  var blockString, continueBlock;
  blockString = $(this).hasClass("btn-danger") ? "block" : "don't block";
  continueBlock = confirm("Are you sure that you wish to " + blockString + " this id");
  if (continueBlock) {
    $(this).toggleClass("btn-danger").toggleClass("btn-success").prev(".inform").toggleClass("blocked");
    if ($(this).hasClass("btn-success")) {
      $(this).prev(".inform").html("<del>" + $(this).prev(".inform").html() + "</del>");
      $(this).html('<i class="icon-unlock"></i> don\'t block');
    } else {
      $(this).prev(".inform").html($(this).prev(".inform").children("del").html());
      $(this).html('<i class="icon-lock"></i> block');
    }
  }
  return e.preventDefault();
});

/*
This function add/remove itens on the modal window visualization of the second widget.
*/


$('.choose-mini-form .close, .open-mini-form, .close-mini-form').live("click", function(e) {
  var $current, $html, $selectedOP;
  if ($(this).hasClass("close-mini-form")) {
    $current = $(this).parent().parent().find(".current");
    if ($current.data("type") === "team" && $(this).parent().find('[class^="input-"]').val() !== "") {
      $current.children(".current-" + $current.data("type")).html($(this).parent().find('[class^="input-"]').val());
    }
    $html = '<select class="input-small" id="tipo-problema">\
                        <option value="">A thing</option>\
                        <option value="urna_nao_liga">another thing</option>\
                        <option value="urna_com_bateria_fraca">other thing</option>\
                      </select>\
                      <input class="ue-number" type="text" placeholder="a input!!" />';
    if ($current.data("type") === "problem" && $(this).parent().find('[class^="input-"]').val() !== "") {
      $(this).parent().parent().find(".current").html($html);
      $selectedOP = $(this).parent().find('[class^="input-"] option:selected');
      $(this).parent().parent().find(".current").children("#tipo-problema").find("option").each(function() {
        if ($(this).html() === $selectedOP.html()) {
          return $(this).attr("selected", "selected");
        }
      });
      $(this).parent().parent().parent().parent().find(".modal-header").append('<span class="label">' + $(this).parent().find('[class^="input-"] option:selected').html() + '</span> <span class="label">this label was added now!</span>');
    }
  }
  $(this).parent().parent().find(".hide").toggleClass("hide");
  $(this).parent().toggleClass("hide");
  return e.preventDefault();
});

/*
More dummy stuff on the modal window visualization of the second widget.
*/


$("#solucao").live("change", function() {
  if ($("#solucao option:selected").data("solution") === "troca") {
    return $(this).next(".ue-number").addClass("show");
  } else {
    return $(this).next(".ue-number").removeClass("show");
  }
});

/*
This function mimmics the AJAX injection of data (aqui simulado pelas variáveis $htmlTransmissao, $htmlSecao, $htmlLocal e $htmlMunicipio) on the 'view data' buttons of some items.
*/


$('[href="#visualizarPessoas"]').live("click", function() {
  var $htmlLocal, $htmlMunicipio, $htmlSecao, $htmlTransmissao;
  $htmlTransmissao = '<h4>Some random people!</h4><br />\
                  <table class="table table-striped table-bordered">\
                    <thead>\
                      <tr>\
                        <th>Name</th>\
                        <th>Phone</th>\
                      </tr>\
                    </thead>\
                    <tbody>\
                      <tr>\
                        <td>José Silvestre</td>\
                        <td>9999-8888</td>\
                      </tr>\
                      <tr>\
                        <td>Creuza Pereira</td>\
                        <td>9898-8989</td>\
                      </tr>\
                    </tbody>\
                  </table>';
  $htmlSecao = '<h4>Other random people</h4><br />\
                  <table class="table table-striped table-bordered">\
                    <thead>\
                      <tr>\
                        <th>Name</th>\
                        <th>Phone</th>\
                        <th>Job</th>\
                      </tr>\
                    </thead>\
                    <tbody>\
                      <tr>\
                        <td>José Silvestre</td>\
                        <td>9999-8888</td>\
                        <td>anything</td>\
                      </tr>\
                      <tr>\
                        <td>Creuza Pereira</td>\
                        <td>9898-8989</td>\
                        <td>nothing</td>\
                      </tr>\
                    </tbody>\
                  </table>';
  $htmlLocal = '<h4>This is some random data</h4><br />\
                  <table class="table table-striped table-bordered">\
                    <thead>\
                      <tr>\
                        <th>Name</th>\
                        <th>Phone</th>\
                        <th>Job</th>\
                      </tr>\
                    </thead>\
                    <tbody>\
                      <tr>\
                        <td>José Silvestre</td>\
                        <td>9999-8888</td>\
                        <td>A</td>\
                      </tr>\
                      <tr>\
                        <td>Creuza Pereira</td>\
                        <td>9898-8989</td>\
                        <td>B</td>\
                      </tr>\
                    </tbody>\
                  </table>';
  $htmlMunicipio = '<h4>Another random thing</h4><br />\
                  <table class="table table-striped table-bordered">\
                    <thead>\
                      <tr>\
                        <th>Name</th>\
                        <th>Phone</th>\
                        <th>Job</th>\
                      </tr>\
                    </thead>\
                    <tbody>\
                      <tr>\
                        <td>José Silvestre</td>\
                        <td>9999-8888</td>\
                        <td>A</td>\
                      </tr>\
                      <tr>\
                        <td>Creuza Pereira</td>\
                        <td>9898-8989</td>\
                        <td>D</td>\
                      </tr>\
                    </tbody>\
                  </table>\
\
                  <h4>Another random data here</h4><br />\
                  <table class="table table-striped table-bordered">\
                    <thead>\
                      <tr>\
                        <th>Name</th>\
                        <th>Phone</th>\
                        <th>Job</th>\
                      </tr>\
                    </thead>\
                    <tbody>\
                      <tr>\
                        <td>Carlos da Silva</td>\
                        <td>9999-8888</td>\
                        <td>T</td>\
                      </tr>\
                      <tr>\
                        <td>João of Nóbrega</td>\
                        <td>9898-8989</td>\
                        <td>E</td>\
                      </tr>\
                    </tbody>\
                  </table>';
  if ($(this).data("type") === "secao") {
    $("#visualizarPessoas").find(".modal-header h3").html("Item A - Item X");
    return $("#visualizarPessoas").find(".modal-body").html($htmlSecao);
  } else if ($(this).data("type") === "local") {
    $("#visualizarPessoas").find(".modal-header h3").html("Item A");
    return $("#visualizarPessoas").find(".modal-body").html($htmlLocal);
  } else if ($(this).data("type") === "municipio") {
    $("#visualizarPessoas").find(".modal-header h3").html("Other Item A");
    return $("#visualizarPessoas").find(".modal-body").html($htmlMunicipio);
  } else if ($(this).data("type") === "transmissao") {
    $("#visualizarPessoas").find(".modal-header h3").html('<span class="label label-success" rel="tooltip" title="Waiting">A</span>\
    014 - Palmas - Colégio Doc Emmett Brown');
    return $("#visualizarPessoas").find(".modal-body").html($htmlTransmissao);
  }
});

/*
This retracts/shows the #message-form
*/


$("#message-form form textarea").on("focus", function() {
  $(this).addClass("retracted");
  $(this).parents("form").find(".as-selections, button").addClass("visible");
  return $(this).parents("#sidebar").find("#messages").addClass("retracted");
});

/*
This resets the #message-form to it's original state when the submit button is clicked.
Also, it shows a little notification.
*/


$("#message-form form button").on("click", function(e) {
  $(this).parents("form").find("textarea").removeClass("retracted").val("");
  $(this).parents("form").find(".as-selections, button").removeClass("visible");
  $(this).parents("#sidebar").find("#messages").removeClass("retracted");
  $(this).parents("form").find(".as-selection-item").remove();
  $(this).parents("form").find(".as-values").val("");
  $(this).parents(".container").prepend('<div class="alert alert-success hide" style="position:fixed; top:47px; left:auto; z-index: 1008">\
      <button class="close" data-dismiss="alert">×</button>\
      Your message has been sent! Or not!\
    </div>');
  $(this).parents(".container").find(".alert").slideToggle('fast');
  return e.preventDefault();
});

/*
Just avoid the form submition.
*/


$("#message-form form").on("submit", function() {
  return false;
});

/*
This function is responsible to show a notification when a form is submitted.
*/


$(".modal .modal-footer .btn-primary, .modal .modal-footer .btn-danger").on("click", function() {
  var $current, mensagem;
  $(this).parents(".container").find(".alert").slideToggle('fast').remove();
  mensagem = "";
  $current = $(this).parents(".modal");
  if ($current.attr("id") === "cadastrarOcorrencia") {
    mensagem = "Some random message";
  } else if ($current.attr("id") === "cadastrarOcorrenciaCorregedoria") {
    mensagem = "Other random message";
  } else if ($current.attr("id") === "revogarPonto") {
    mensagem = "Yet another message";
  }
  $(this).parents(".container").prepend("<div class=\"alert alert-success hide\" style=\"position:fixed; top:47px; left:auto; z-index: 1008\">      <button class=\"close\" data-dismiss=\"alert\">×</button>      " + mensagem + "    </div>");
  return $(this).parents(".container").find(".alert").slideToggle('fast');
});

/*
This adds a specila navigation to the resolutions between 800x600/1024x768.
*/


$("#mobile-widgets-nav a").live("click", function(e) {
  if ($(this).hasClass("btn-next")) {
    $("#mobile-widgets-nav .btn-prev").removeClass("disabled");
    if (!$(this).hasClass("disabled")) {
      if (!$(this).parents(".widgets").find('[class^="widget-"].current').hasClass("widget-ocorrencia")) {
        $(this).parents(".widgets").find('[class^="widget-"].current').removeClass("current").addClass("past").next().addClass("current");
      } else {
        $(this).parents(".widgets").find('[class^="widget-"].current').removeClass("current").addClass("past").parent().next().find(".widget-totalizacao").addClass("current");
      }
      $(this).parents("#mobile-widgets-nav").find("#pages .current").removeClass("current").next().addClass("current");
      if ($(this).parents(".widgets").find('[class^="widget-"].current').hasClass("widget-corregedoria")) {
        $(this).addClass("disabled");
      }
    }
  } else if ($(this).hasClass("btn-prev")) {
    $("#mobile-widgets-nav .btn-next").removeClass("disabled");
    if (!$(this).hasClass("disabled")) {
      if (!$(this).parents(".widgets").find('[class^="widget-"].current').hasClass("widget-totalizacao")) {
        $(this).parents(".widgets").find('[class^="widget-"].current').removeClass("current").prev().removeClass("past").addClass("current");
      } else {
        $(this).parents(".widgets").find('[class^="widget-"].current').removeClass("current").parent().prev().find(".widget-ocorrencia").removeClass("past").addClass("current");
      }
      $(this).parents("#mobile-widgets-nav").find("#pages .current").removeClass("current").prev().addClass("current");
      if ($(this).parents(".widgets").find('[class^="widget-"].current').hasClass("widget-transmissao")) {
        $(this).addClass("disabled");
      }
    }
  }
  return e.preventDefault();
});

/*
This function toggles the messages widget.
*/


$("#sidebar-toggle a").on("click", function(e) {
  $(this).parent().toggleClass("nl");
  $(this).parent().parent().find("#sidebar").toggleClass("retracted");
  if ($(this).parent().hasClass("nl")) {
    $(this).html('<i class="icon-comment"></i> <i class="icon-caret-right"></i>');
  } else {
    $(this).html('<i class="icon-caret-left"></i> <i class="icon-comment-alt"></i>');
  }
  return $(this).parents(".row").find(".widgets").toggleClass("expanded");
});

/*
This function will replace the targeted radio buttons to a specil 'switch' element.
*/


$('input[type=radio].mini-switch, input[type=checkbox].mini-switch').hide().after('<span class="mini-switch-replace"></span>');
